print(" git does not know automatically about remote updates")
print ( "more prints to test git fetch")
print ( "you can make changes locally and push them to remote")
print(" remotely a change happened by opther developers")
print("weird local commit not pushed yet")
